function list_click(b){b=document.getElementsByName(b)[0];b.checked=!0==b.checked?!1:!0}function listOUchanged(b,a){location.href="list.php?type="+b+"&suffix="+a.options[a.selectedIndex].value}function listPageNumberKeyPress(b,a){var c=jQuery("#listNavPage").val();return 13==a.keyCode?(a.preventDefault&&a.preventDefault(),location.href=b+"&page="+c,!1):!0}
function listResizeITabContentDiv(){var b=document.getElementById("listTabContentArea"),a=document.documentElement.clientHeight,a=a-b.offsetTop,a=a-105;b.style.height=a+"px";var c=document.getElementById("listScrollArea");c.style.height=a-(c.offsetTop-b.offsetTop)+"px"}
function listShowSettingsDialog(b,a,c){var d={};d[a]=function(){document.forms.settingsDialogForm.submit()};d[c]=function(){jQuery(this).dialog("close")};jQuery("#settingsDialog").dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:d,width:"auto"})}
function SubmitForm(b,a){if(13==a.keyCode){a.preventDefault&&a.preventDefault();a.returnValue&&(a.returnValue=!1);if(window.lastKeyCode&&(33==window.lastKeyCode||34==window.lastKeyCode||38==window.lastKeyCode||40==window.lastKeyCode))return window.lastKeyCode=a.keyCode,!0;document.getElementsByName(b)[0].click();return!1}window.lastKeyCode=a.keyCode;return!0}
function addResizeHandler(b,a,c){jQuery(b).click(function(){jQuery(b).hasClass("imgExpanded")?jQuery(b).animate({height:a}):jQuery(b).animate({height:c});jQuery(b).toggleClass("imgExpanded")})}
function list_switchAccountSelection(){jQuery("input.accountBoxUnchecked").prop("checked",!0);jQuery("input.accountBoxChecked").prop("checked",!1);nowChecked=jQuery(".accountBoxUnchecked");nowUnchecked=jQuery(".accountBoxChecked");nowChecked.addClass("accountBoxChecked");nowChecked.removeClass("accountBoxUnchecked");nowUnchecked.addClass("accountBoxUnchecked");nowUnchecked.removeClass("accountBoxChecked")}
function loginProfileChanged(b){location.href="login.php?useProfile="+b.options[b.selectedIndex].value}
function profileShowDeleteDialog(b,a,c,d,f){f=jQuery("[name="+f+"]").val();jQuery("#deleteText").text(f);jQuery("#profileDeleteType").val(d);jQuery("#profileDeleteName").val(f);d={};d[a]=function(){document.forms.deleteProfileForm.submit()};d[c]=function(){jQuery(this).dialog("close")};jQuery("#deleteProfileDialog").dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:d,width:"auto"})}
function showSimpleDialog(b,a,c,d,f){var e={};a&&(e[a]=function(){document.forms[d].submit()});e[c]=function(){jQuery(this).dialog("close")};jQuery("#"+f).dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:e,width:"auto"})}
function passwordShowChangeDialog(b,a,c,d,f){var e={};e[a]=function(){passwordHandleInput("false",f)};e[d]=function(){passwordHandleInput("true",f)};e[c]=function(){jQuery("#passwordDialogMessageArea").html("");jQuery(this).dialog("close")};jQuery("#passwordDialog").dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:e,width:"auto"});document.getElementsByName("newPassword1")[0].focus()}
function passwordHandleInput(b,a){var c=[];jQuery("#passwordDialog").find(":checked").each(function(){c.push(jQuery(this).prop("name"))});var d=jQuery("#passwordDialog").find("[name=newPassword1]").val(),f=jQuery("#passwordDialog").find("[name=newPassword2]").val(),e=jQuery("input[name=lamForcePasswordChange]").prop("checked"),g=jQuery("input[name=lamPasswordChangeSendMail]").prop("checked"),h="";jQuery("#passwordDialog").find("[name=lamPasswordChangeSendMailAddress]")&&(h=jQuery("#passwordDialog").find("[name=lamPasswordChangeSendMailAddress]").val());
jQuery.post(a,{jsonInput:{modules:c,password1:d,password2:f,random:b,forcePasswordChange:e,sendMail:g,sendMailAlternateAddress:h}},function(a){passwordHandleReply(a)},"json")}
function passwordHandleReply(b){"false"==b.errorsOccured?(jQuery("#passwordDialogMessageArea").html(""),jQuery("#passwordDialog").dialog("close"),jQuery("#passwordMessageArea").html(b.messages),b.forcePasswordChange&&jQuery("#forcePasswordChangeOption").attr("checked","checked")):jQuery("#passwordDialogMessageArea").html(b.messages)}
function showConfirmationDialog(b,a,c,d,f,e){var g={};g[a]=function(){jQuery("#"+d).dialog("close");e&&jQuery("#"+e).val("ok");appendDialogInputsToFormAndSubmit(d,f)};g[c]=function(){e&&jQuery("#"+e).val("cancel");jQuery(this).dialog("close")};jQuery("#"+d).dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:g,width:"auto"})}
function appendDialogInputsToFormAndSubmit(b,a){jQuery("#"+b+" :input").each(function(){jQuery(this).addClass("hidden");jQuery(this).appendTo(document.forms[a])});document.forms[a].submit()}function confirmOrStopProcessing(b,a){return!confirm(b)?(a.preventDefault&&a.preventDefault(),a.returnValue&&(a.returnValue=!1),!1):!0}
function equalWidth(b){for(var a=0,c=0;c<b.length;++c)jQuery(b[c]).width()>a&&(a=jQuery(b[c]).width());if(!(5>a))for(c=0;c<b.length;++c)jQuery(b[c]).css({width:a-(jQuery(b[c]).outerWidth()-jQuery(b[c]).width())})}function equalHeight(b){for(var a=0,c=0;c<b.length;++c)jQuery(b[c]).height()>a&&(a=jQuery(b[c]).height());for(c=0;c<b.length;++c)jQuery(b[c]).css({height:a-(jQuery(b[c]).outerHeight()-jQuery(b[c]).height())})}
function showDistributionDialog(b,a,c,d,f,e){var g={},h="";"export"==f?(jQuery("#name_"+d).val(jQuery("#"+e).val()),h="exportDialog_"+d,g[a]=function(){document.forms["exportDialogForm_"+d].submit()}):"import"==f&&(h="importDialog_"+d,g[a]=function(){document.forms["importDialogForm_"+d].submit()});g[c]=function(){jQuery(this).dialog("close")};jQuery("#"+h).dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:g,width:"auto"});"export"==f?equalWidth(["#passwd_"+d,"#destServerProfiles_"+
d]):"import"==f&&equalWidth(["#passwd_"+d,"#importProfiles"])}function saveScrollPosition(b){var a=jQuery(window).scrollTop(),c=jQuery(window).scrollLeft();jQuery("<input>").attr({type:"hidden",name:"scrollPositionTop",value:a}).appendTo(jQuery("#"+b));jQuery("<input>").attr({type:"hidden",name:"scrollPositionLeft",value:c}).appendTo(jQuery("#"+b))}
function bindShowNewZoneDialog(b,a,c){var d={};d[a]=function(){document.forms.newBindZoneDialogForm.submit()};d[c]=function(){jQuery(this).dialog("close")};jQuery("#newBindZoneDialog").dialog({modal:!0,title:b,dialogClass:"defaultBackground",buttons:d,width:"auto"})}jQuery(document).ready(function(){jQuery(document).tooltip({items:"[helpdata]",content:function(){var b=$(this),a;a='<table><tr><th class="help">'+b.attr("helptitle");a=a+'</th></tr><td class="help">'+b.attr("helpdata");return a+="</td></tr></table>"}})});
function checkFieldsHaveSameValues(b,a){var c=jQuery("#"+b),d=jQuery("#"+a),f=function(){var a=c.val(),b=d.val();""==a&&""==b?(c.removeClass("markFail"),c.removeClass("markOk")):a==b?(c.removeClass("markFail"),c.addClass("markOk")):(c.addClass("markFail"),c.removeClass("markOk"))};jQuery(c).keyup(f);jQuery(d).keyup(f)}
function checkPasswordStrength(b,a){var c=jQuery("#"+b);jQuery(c).keyup(function(){var d={password:c.val()};jQuery.post(a+"&function=passwordStrengthCheck",{jsonInput:d},function(a){checkPasswordStrengthHandleReply(a,b)},"json")})}
function checkPasswordStrengthHandleReply(b,a){var c=jQuery("#"+a);!0==b.result?(c.removeClass("markFail"),c.addClass("markOk"),c.prop("title","")):""==c.val()?(c.removeClass("markFail"),c.removeClass("markOk")):(c.addClass("markFail"),c.removeClass("markOk"),c.prop("title",b.result))}function updateModulePositions(b,a,c){var d=jQuery("#"+b).val().split(",");if(c>a){for(var f=d[a],e=a;e<c;e++)d[e]=d[e+1];d[c]=f}if(c<a){f=d[a];for(e=a;e>c;e--)d[e]=d[e-1];d[c]=f}jQuery("#"+b).val(d.join(","))}
function filterSelect(b,a,c){if(!jQuery("#"+a).data("options")){var d=[];jQuery("#"+a).find("option").each(function(){d.push({value:$(this).val(),text:$(this).text()})});jQuery("#"+a).data("options",d)}var f=jQuery("#"+a).empty().scrollTop(0).data("options");b=jQuery.trim(jQuery("#"+b).val());var e=RegExp(b,"gi");jQuery.each(f,function(b){b=f[b];null!==b.text.match(e)&&jQuery("#"+a).append(jQuery("<option>").text(b.text).val(b.value))})}window.lam=window.lam||{};
window.lam.upload=window.lam.upload||{};window.lam.upload.continueUpload=function(b){jQuery.ajax({url:b,method:"POST",data:"jsonInput="}).done(function(a){a.accountsFinished?a.postActionsFinished?a.pdfFinished||window.lam.upload.printPDFStatus(a):window.lam.upload.printPostActionStatus(a):window.lam.upload.printBasicStatus(a);a.allDone?window.lam.upload.uploadDone(a):window.lam.upload.continueUpload(b)})};
window.lam.upload.printBasicStatus=function(b){var a;a='<div class="title">'+('<h2 class="titleText">'+b.title+"</h2>");a+='</div><div id="progressbarGeneral"></div>';jQuery("#uploadContent").html(a);jQuery("#progressbarGeneral").progressbar({value:b.accountsProgress})};
window.lam.upload.printPostActionStatus=function(b){var a;a='<div class="title">'+('<h2 class="titleText">'+b.title+"</h2>");a+='</div><div id="progressbarGeneral"></div>';b.postActionsTitle&&(a+="<h2>"+b.postActionsTitle+"</h2>",a+='<div id="progressbarPostActions"></div>');jQuery("#uploadContent").html(a);jQuery("#progressbarGeneral").progressbar({value:100});b.postActionsTitle&&jQuery("#progressbarPostActions").progressbar({value:b.postActionsProgress})};
window.lam.upload.printPDFStatus=function(b){var a;a='<div class="title">'+('<h2 class="titleText">'+b.title+"</h2>");a+='</div><div id="progressbarGeneral"></div>';a+="<h2>"+b.titlePDF+"</h2>";a+='<div id="progressbarPDF"></div>';jQuery("#uploadContent").html(a);jQuery("#progressbarGeneral").progressbar({value:100});jQuery("#progressbarPDF").progressbar({value:b.pdfProgress})};
window.lam.upload.uploadDone=function(b){if(b.errorHtml){var a;a='<div class="subTitle">'+('<h4  class="subTitleText">'+b.titleErrors+"</h4>");a=a+"</div>"+b.errorHtml;jQuery("#uploadContent").html(a)}else top.location.href="../lists/list.php?type="+b.typeId+"&uploadAllOk"};jQuery(document).ready(function(){var b=0;jQuery(".lamEqualHeightTabContent").each(function(){jQuery(this).height()>b&&(b=jQuery(this).height())});jQuery(".lamEqualHeightTabContent").each(function(){jQuery(this).css({height:b})})});

